export interface FieldConfig {
  labelKey: string;
  type: "text" | "number" | "select" | "textarea" | "boolean" | "combobox" | "richtext";
  placeholder?: string;
  options?: { value: string; label: string }[];
  allowCustom?: boolean;
  helpKey?: string;
  width?: "full" | "half" | "third";
  optional?: boolean;
  /** v2: worker types this field applies to. Omitted = shown for all worker types. */
  workerTypes?: string[];
}

export type FieldConfigs = Record<string, FieldConfig>;

// Worker types that render (and therefore can supply) the vacation-days field.
// Self-employed freelancers have no statutory paid leave, so the field is hidden
// for them. Exported so the validation schema requires vacationDays for EXACTLY
// the worker types that can see it — keeping the schema and the form in lockstep.
export const VACATION_DAYS_WORKER_TYPES = ["whiteCollar", "blueCollar", "intern", "phdResearcher"];

// Field configurations function generator that accepts translation function
export const createFieldConfigs = (t: (key: string) => string): FieldConfigs => ({
  age: {
    labelKey: "sections.personal.age",
    type: "number",
    placeholder: t("placeholders.age"),
    helpKey: "help.age",
    width: "half",
  },
  education: {
    labelKey: "sections.personal.education",
    type: "select",
    placeholder: t("placeholders.education"),
    options: [
      {
        value: "highSchool",
        label: t("formOptions.education.highSchool"),
      },
      {
        value: "associate",
        label: t("formOptions.education.associate"),
      },
      {
        value: "bachelor",
        label: t("formOptions.education.bachelor"),
      },
      { value: "master", label: t("formOptions.education.master") },
      { value: "phd", label: t("formOptions.education.phd") },
      {
        value: "professional",
        label: t("formOptions.education.professional"),
      },
      {
        value: "vocational",
        label: t("formOptions.education.vocational"),
      },
      {
        value: "someCollege",
        label: t("formOptions.education.someCollege"),
      },
    ],
    helpKey: "help.education",
    width: "half",
  },
  degreeId: {
    labelKey: "sections.personal.degree",
    type: "combobox",
    placeholder: t("placeholders.degree"),
    helpKey: "help.degree",
    width: "full",
    optional: true,
    allowCustom: false,
  },
  workExperience: {
    labelKey: "sections.personal.workExperience",
    type: "number",
    placeholder: t("placeholders.workExperience"),
    helpKey: "help.workExperience",
    width: "half",
  },
  civilStatus: {
    labelKey: "sections.personal.civilStatus",
    type: "select",
    placeholder: t("placeholders.civilStatus"),
    options: [
      { value: "single", label: t("formOptions.civilStatus.single") },
      { value: "cohabiting", label: t("formOptions.civilStatus.cohabiting") },
      { value: "civilUnion", label: t("formOptions.civilStatus.civilUnion") },
      { value: "married", label: t("formOptions.civilStatus.married") },
      { value: "divorced", label: t("formOptions.civilStatus.divorced") },
      { value: "widowed", label: t("formOptions.civilStatus.widowed") },
    ],
    helpKey: "help.civilStatus",
    width: "half",
  },
  dependents: {
    labelKey: "sections.personal.dependents",
    type: "number",
    placeholder: t("placeholders.dependents"),
    helpKey: "help.dependents",
    width: "full",
  },
  sector: {
    labelKey: "sections.employer.sector",
    type: "select",
    placeholder: t("placeholders.sector"),
    options: [
      { value: "Aerospace", label: t("formOptions.sector.Aerospace") },
      { value: "Agriculture", label: t("formOptions.sector.Agriculture") },
      { value: "Automotive", label: t("formOptions.sector.Automotive") },
      { value: "Biotech", label: t("formOptions.sector.Biotech") },
      { value: "Construction", label: t("formOptions.sector.Construction") },
      { value: "Consulting", label: t("formOptions.sector.Consulting") },
      { value: "Education", label: t("formOptions.sector.Education") },
      { value: "Energy", label: t("formOptions.sector.Energy") },
      { value: "Entertainment", label: t("formOptions.sector.Entertainment") },
      { value: "Finance", label: t("formOptions.sector.Finance") },
      { value: "FMCG", label: t("formOptions.sector.FMCG") },
      { value: "Healthcare", label: t("formOptions.sector.Healthcare") },
      { value: "Hospitality", label: t("formOptions.sector.Hospitality") },
      { value: "HR", label: t("formOptions.sector.HR") },
      { value: "IT", label: t("formOptions.sector.IT") },
      { value: "Legal", label: t("formOptions.sector.Legal") },
      { value: "Manufacturing", label: t("formOptions.sector.Manufacturing") },
      { value: "Media", label: t("formOptions.sector.Media") },
      { value: "Nonprofit", label: t("formOptions.sector.Nonprofit") },
      { value: "Other", label: t("formOptions.sector.Other") },
      { value: "Pharmaceutical", label: t("formOptions.sector.Pharmaceutical") },
      { value: "Port", label: t("formOptions.sector.Port") },
      { value: "Public Affairs", label: t("formOptions.sector.Public Affairs") },
      { value: "Public Sector", label: t("formOptions.sector.Public Sector") },
      { value: "RealEstate", label: t("formOptions.sector.RealEstate") },
      { value: "Research", label: t("formOptions.sector.Research") },
      { value: "Retail", label: t("formOptions.sector.Retail") },
      { value: "Telecommunications", label: t("formOptions.sector.Telecommunications") },
      { value: "Technology/SaaS", label: t("formOptions.sector.Technology/SaaS") },
      { value: "Transportation", label: t("formOptions.sector.Transportation") },
      { value: "Chemical", label: t("formOptions.sector.Chemical") },
      { value: "Logistics", label: t("formOptions.sector.Logistics") },
    ].sort((a, b) => a.label.localeCompare(b.label)),
    helpKey: "help.sector",
    width: "half",
  },
  employeeCount: {
    labelKey: "sections.employer.employeeCount",
    type: "select",
    placeholder: t("placeholders.employeeCount"),
    options: [
      { value: "1-10", label: t("formOptions.employeeCount.range1") },
      { value: "11-50", label: t("formOptions.employeeCount.range2") },
      { value: "51-200", label: t("formOptions.employeeCount.range3") },
      { value: "201-500", label: t("formOptions.employeeCount.range4") },
      { value: "501-1k", label: t("formOptions.employeeCount.range5") },
      { value: "1k-5k", label: t("formOptions.employeeCount.range6") },
      { value: "5k-10k", label: t("formOptions.employeeCount.range7") },
      { value: "10k-50k", label: t("formOptions.employeeCount.range8") },
      { value: "50k-100k", label: t("formOptions.employeeCount.range9") },
      { value: "100k-500k", label: t("formOptions.employeeCount.range10") },
      { value: "500k+", label: t("formOptions.employeeCount.range11") },
    ],
    helpKey: "help.employeeCount",
    width: "half",
  },
  multinational: {
    labelKey: "sections.employer.multinational",
    type: "boolean",
    options: [
      { value: "yes", label: t("options.yes") },
      { value: "no", label: t("options.no") },
    ],
    helpKey: "help.multinational",
  },
  publiclyListed: {
    labelKey: "sections.employer.publiclyListed",
    type: "boolean",
    options: [
      { value: "yes", label: t("options.yes") },
      { value: "no", label: t("options.no") },
    ],
    helpKey: "help.publiclyListed",
    optional: true,
  },
  jobTitle: {
    labelKey: "sections.job.jobTitle",
    type: "text",
    placeholder: t("placeholders.jobTitle"),
    helpKey: "help.jobTitle",
    width: "full",
  },
  seniority: {
    labelKey: "sections.job.seniority",
    type: "number",
    placeholder: t("placeholders.seniority"),
    helpKey: "help.seniority",
    width: "half",
  },
  jobDescription: {
    labelKey: "sections.job.jobDescription",
    type: "textarea",
    placeholder: t("placeholders.jobDescription"),
    helpKey: "help.jobDescription",
    optional: true,
  },
  officialHours: {
    labelKey: "sections.workingHours.officialHours",
    type: "number",
    placeholder: t("placeholders.officialHours"),
    helpKey: "help.officialHours",
    width: "half",
  },
  averageHours: {
    labelKey: "sections.workingHours.averageHours",
    type: "number",
    placeholder: t("placeholders.averageHours"),
    helpKey: "help.averageHours",
    width: "half",
  },
  shiftDescription: {
    labelKey: "sections.workingHours.shiftDescription",
    type: "text",
    placeholder: t("placeholders.shiftDescription"),
    helpKey: "help.shiftDescription",
    width: "half",
    optional: true,
  },
  onCall: {
    labelKey: "sections.workingHours.onCall",
    type: "text",
    placeholder: t("placeholders.onCall"),
    helpKey: "help.onCall",
    width: "half",
    optional: true,
  },
  vacationDays: {
    labelKey: "sections.vacation.vacationDays",
    type: "number",
    placeholder: t("placeholders.vacationDays"),
    helpKey: "help.vacationDays",
    width: "half",
    // Self-employed freelancers have no statutory paid leave.
    workerTypes: VACATION_DAYS_WORKER_TYPES,
  },
  workerType: {
    labelKey: "sections.employment.workerType",
    type: "select",
    placeholder: t("placeholders.workerType"),
    options: [
      { value: "whiteCollar", label: t("formOptions.workerType.whiteCollar") },
      { value: "blueCollar", label: t("formOptions.workerType.blueCollar") },
      { value: "freelancer", label: t("formOptions.workerType.freelancer") },
      { value: "intern", label: t("formOptions.workerType.intern") },
      { value: "phdResearcher", label: t("formOptions.workerType.phdResearcher") },
    ],
    helpKey: "help.workerType",
    width: "half",
  },
  contractType: {
    labelKey: "sections.employment.contractType",
    type: "select",
    placeholder: t("placeholders.contractType"),
    options: [
      { value: "permanent", label: t("formOptions.contractType.permanent") },
      { value: "fixedTerm", label: t("formOptions.contractType.fixedTerm") },
      { value: "interim", label: t("formOptions.contractType.interim") },
      { value: "internship", label: t("formOptions.contractType.internship") },
      { value: "freelance", label: t("formOptions.contractType.freelance") },
    ],
    helpKey: "help.contractType",
    width: "half",
    optional: true,
  },
  contractDurationMonths: {
    labelKey: "sections.employment.contractDurationMonths",
    type: "number",
    placeholder: t("placeholders.contractDurationMonths"),
    helpKey: "help.contractDurationMonths",
    width: "half",
    optional: true,
  },
  salaryBasis: {
    labelKey: "sections.salary.salaryBasis",
    type: "select",
    placeholder: t("placeholders.salaryBasis"),
    options: [
      { value: "gross", label: t("formOptions.salaryBasis.gross") },
      { value: "net", label: t("formOptions.salaryBasis.net") },
      { value: "both", label: t("formOptions.salaryBasis.both") },
    ],
    helpKey: "help.salaryBasis",
    width: "third",
    // Freelancers bill day rates ex-VAT and PhD bursaars receive a (tax-exempt)
    // bursary — the gross/net basis only applies to salaried employees.
    workerTypes: ["whiteCollar", "blueCollar", "intern"],
  },
  grossSalary: {
    labelKey: "sections.salary.grossSalary",
    type: "number",
    placeholder: t("placeholders.grossSalary"),
    helpKey: "help.grossSalary",
    width: "third",
    workerTypes: ["whiteCollar", "intern"],
  },
  netSalary: {
    labelKey: "sections.salary.netSalary",
    type: "number",
    placeholder: t("placeholders.netSalary"),
    helpKey: "help.netSalary",
    width: "third",
    workerTypes: ["whiteCollar", "intern", "blueCollar"],
  },
  netCompensation: {
    labelKey: "sections.salary.netCompensation",
    type: "number",
    placeholder: t("placeholders.netCompensation"),
    helpKey: "help.netCompensation",
    width: "third",
    workerTypes: ["whiteCollar", "intern"],
  },
  fixedGrossSalary: {
    labelKey: "sections.salary.fixedGrossSalary",
    type: "number",
    placeholder: t("placeholders.fixedGrossSalary"),
    helpKey: "help.fixedGrossSalary",
    width: "third",
    optional: true,
    workerTypes: ["whiteCollar", "intern"],
  },
  variableGrossSalary: {
    labelKey: "sections.salary.variableGrossSalary",
    type: "number",
    placeholder: t("placeholders.variableGrossSalary"),
    helpKey: "help.variableGrossSalary",
    width: "third",
    optional: true,
    workerTypes: ["whiteCollar", "intern"],
  },
  hourlyRate: {
    labelKey: "sections.salary.hourlyRate",
    type: "number",
    placeholder: t("placeholders.hourlyRate"),
    helpKey: "help.hourlyRate",
    width: "third",
    workerTypes: ["blueCollar"],
  },
  dayRate: {
    labelKey: "sections.salary.dayRate",
    type: "number",
    placeholder: t("placeholders.dayRate"),
    helpKey: "help.dayRate",
    width: "third",
    workerTypes: ["freelancer"],
  },
  agencyCutPercent: {
    labelKey: "sections.salary.agencyCutPercent",
    type: "number",
    placeholder: t("placeholders.agencyCutPercent"),
    helpKey: "help.agencyCutPercent",
    width: "third",
    optional: true,
    workerTypes: ["freelancer"],
  },
  clientDayBudget: {
    labelKey: "sections.salary.clientDayBudget",
    type: "number",
    placeholder: t("placeholders.clientDayBudget"),
    helpKey: "help.clientDayBudget",
    width: "third",
    optional: true,
    workerTypes: ["freelancer"],
  },
  bursaryAmount: {
    labelKey: "sections.salary.bursaryAmount",
    type: "number",
    placeholder: t("placeholders.bursaryAmount"),
    helpKey: "help.bursaryAmount",
    width: "third",
    workerTypes: ["phdResearcher"],
  },
  virtualGrossSalary: {
    labelKey: "sections.salary.virtualGrossSalary",
    type: "number",
    placeholder: t("placeholders.virtualGrossSalary"),
    helpKey: "help.virtualGrossSalary",
    width: "third",
    optional: true,
    workerTypes: ["phdResearcher"],
  },
  thirteenthMonth: {
    labelKey: "sections.benefits.thirteenthMonth",
    type: "select",
    placeholder: t("placeholders.thirteenthMonth"),
    options: [
      { value: "Full", label: t("formOptions.thirteenthMonth.full") },
      {
        value: "Partial",
        label: t("formOptions.thirteenthMonth.partial"),
      },
      { value: "None", label: t("formOptions.thirteenthMonth.none") },
    ],
    helpKey: "help.thirteenthMonth",
    width: "third",
    workerTypes: ["whiteCollar", "blueCollar", "intern", "phdResearcher"],
  },
  mealVouchers: {
    labelKey: "sections.benefits.mealVouchers",
    type: "number",
    placeholder: t("placeholders.mealVouchers"),
    helpKey: "help.mealVouchers",
    width: "third",
    workerTypes: ["whiteCollar", "blueCollar", "intern", "phdResearcher"],
  },
  ecoCheques: {
    labelKey: "sections.benefits.ecoCheques",
    type: "number",
    placeholder: t("placeholders.ecoCheques"),
    helpKey: "help.ecoCheques",
    width: "third",
    workerTypes: ["whiteCollar", "blueCollar", "intern", "phdResearcher"],
  },
  groupInsurance: {
    labelKey: "sections.benefits.groupInsurance",
    type: "text",
    placeholder: t("placeholders.groupInsurance"),
    helpKey: "help.groupInsurance",
    width: "half",
    workerTypes: ["whiteCollar", "blueCollar", "intern", "phdResearcher"],
  },
  hasCompanyCar: {
    labelKey: "sections.benefits.hasCompanyCar",
    type: "boolean",
    options: [
      { value: "yes", label: t("options.yes") },
      { value: "no", label: t("options.no") },
    ],
    helpKey: "help.hasCompanyCar",
    width: "full",
  },
  companyCarModel: {
    labelKey: "sections.benefits.companyCarModel",
    type: "text",
    placeholder: t("placeholders.companyCarModel"),
    helpKey: "help.companyCarModel",
    width: "third",
    optional: true,
  },
  companyCarFuelType: {
    labelKey: "sections.benefits.companyCarFuelType",
    type: "select",
    placeholder: t("placeholders.companyCarFuelType"),
    options: [
      { value: "electric", label: t("formOptions.carFuelType.electric") },
      { value: "hybrid", label: t("formOptions.carFuelType.hybrid") },
      { value: "fuel", label: t("formOptions.carFuelType.fuel") },
    ],
    helpKey: "help.companyCarFuelType",
    width: "third",
  },
  companyCarCardScope: {
    labelKey: "sections.benefits.companyCarCardScope",
    type: "select",
    placeholder: t("placeholders.companyCarCardScope"),
    options: [
      { value: "belgium", label: t("formOptions.carCardScope.belgium") },
      { value: "benelux", label: t("formOptions.carCardScope.benelux") },
      { value: "europe", label: t("formOptions.carCardScope.europe") },
    ],
    helpKey: "help.companyCarCardScope",
    width: "third",
  },
  hasEquity: {
    labelKey: "sections.benefits.hasEquity",
    type: "boolean",
    options: [
      { value: "yes", label: t("options.yes") },
      { value: "no", label: t("options.no") },
    ],
    helpKey: "help.hasEquity",
    width: "full",
  },
  otherInsurances: {
    labelKey: "sections.benefits.otherInsurances",
    type: "text",
    placeholder: t("placeholders.otherInsurances"),
    helpKey: "help.otherInsurances",
    width: "half",
    optional: true,
  },
  otherBenefits: {
    labelKey: "sections.benefits.otherBenefits",
    type: "textarea",
    placeholder: t("sections.benefits.otherBenefitsPlaceholder"),
    helpKey: "help.otherBenefits",
    optional: true,
  },
  locationGranularity: {
    labelKey: "sections.commute.locationGranularity",
    type: "select",
    placeholder: t("placeholders.locationGranularity"),
    options: [
      { value: "country", label: t("formOptions.locationGranularity.country") },
      { value: "province", label: t("formOptions.locationGranularity.province") },
      { value: "city", label: t("formOptions.locationGranularity.city") },
    ],
    helpKey: "help.locationGranularity",
    width: "half",
    optional: true,
  },
  workProvince: {
    labelKey: "sections.commute.workProvince",
    type: "select",
    placeholder: t("placeholders.workProvince"),
    options: [
      { value: "Antwerp", label: t("formOptions.beProvince.antwerp") },
      { value: "East Flanders", label: t("formOptions.beProvince.eastFlanders") },
      { value: "Flemish Brabant", label: t("formOptions.beProvince.flemishBrabant") },
      { value: "Limburg", label: t("formOptions.beProvince.limburg") },
      { value: "West Flanders", label: t("formOptions.beProvince.westFlanders") },
      { value: "Hainaut", label: t("formOptions.beProvince.hainaut") },
      { value: "Liège", label: t("formOptions.beProvince.liege") },
      { value: "Luxembourg", label: t("formOptions.beProvince.luxembourg") },
      { value: "Namur", label: t("formOptions.beProvince.namur") },
      { value: "Walloon Brabant", label: t("formOptions.beProvince.walloonBrabant") },
      { value: "Brussels-Capital", label: t("formOptions.beProvince.brussels") },
    ],
    helpKey: "help.workProvince",
    width: "half",
    optional: true,
  },
  residenceCountry: {
    labelKey: "sections.commute.residenceCountry",
    type: "select",
    placeholder: t("placeholders.residenceCountry"),
    // Cross-border workers: residence may differ from the work country, so this
    // includes neighbours, not just the countries we currently collect data for.
    options: [
      { value: "Belgium", label: t("formOptions.residenceCountry.belgium") },
      { value: "Netherlands", label: t("formOptions.residenceCountry.netherlands") },
      { value: "Germany", label: t("formOptions.residenceCountry.germany") },
      { value: "France", label: t("formOptions.residenceCountry.france") },
      { value: "Luxembourg", label: t("formOptions.residenceCountry.luxembourg") },
    ],
    helpKey: "help.residenceCountry",
    width: "half",
    optional: true,
  },
  workCity: {
    labelKey: "sections.commute.workCity",
    type: "text",
    placeholder: t("placeholders.workCity"),
    helpKey: "help.workCity",
    width: "half",
    optional: true,
  },
  commuteUnit: {
    labelKey: "sections.commute.commuteUnit",
    type: "select",
    placeholder: t("placeholders.commuteUnit"),
    options: [
      { value: "km", label: t("formOptions.commuteUnit.km") },
      { value: "minutes", label: t("formOptions.commuteUnit.minutes") },
    ],
    helpKey: "help.commuteUnit",
    width: "half",
    optional: true,
  },
  commuteDistance: {
    labelKey: "sections.commute.commuteDistance",
    type: "text",
    placeholder: t("placeholders.commuteDistance"),
    helpKey: "help.commuteDistance",
    width: "half",
  },
  commuteTimeMinutes: {
    labelKey: "sections.commute.commuteTimeMinutes",
    type: "number",
    placeholder: t("placeholders.commuteTimeMinutes"),
    helpKey: "help.commuteTimeMinutes",
    width: "half",
    optional: true,
  },
  commuteMethod: {
    labelKey: "sections.commute.commuteMethod",
    type: "text",
    placeholder: t("placeholders.commuteMethod"),
    helpKey: "help.commuteMethod",
    width: "half",
  },
  commuteCompensation: {
    labelKey: "sections.commute.commuteCompensation",
    type: "text",
    placeholder: t("placeholders.commuteCompensation"),
    helpKey: "help.commuteCompensation",
    width: "half",
  },
  teleworkDays: {
    labelKey: "sections.workLife.teleworkDays",
    type: "number",
    placeholder: t("placeholders.teleworkDays"),
    helpKey: "help.teleworkDays",
    width: "half",
  },
  dayOffEase: {
    labelKey: "sections.workLife.dayOffEase",
    type: "select",
    placeholder: t("placeholders.dayOffEase"),
    options: [
      { value: "veryEasy", label: t("formOptions.dayOffEase.veryEasy") },
      { value: "easy", label: t("formOptions.dayOffEase.easy") },
      { value: "moderate", label: t("formOptions.dayOffEase.moderate") },
      { value: "hard", label: t("formOptions.dayOffEase.hard") },
      { value: "veryHard", label: t("formOptions.dayOffEase.veryHard") },
      { value: "situational", label: t("formOptions.dayOffEase.situational") },
      { value: "impossible", label: t("formOptions.dayOffEase.impossible") },
    ],
    helpKey: "help.dayOffEase",
    width: "half",
  },
  stressLevel: {
    labelKey: "sections.workLife.stressLevel",
    type: "select",
    placeholder: t("placeholders.stressLevel"),
    options: [
      { value: "veryLow", label: t("formOptions.stressLevel.veryLow") },
      { value: "low", label: t("formOptions.stressLevel.low") },
      { value: "moderate", label: t("formOptions.stressLevel.moderate") },
      { value: "high", label: t("formOptions.stressLevel.high") },
      { value: "veryHigh", label: t("formOptions.stressLevel.veryHigh") },
      { value: "situational", label: t("formOptions.stressLevel.situational") },
      { value: "none", label: t("formOptions.stressLevel.none") },
    ],
    helpKey: "help.stressLevel",
    width: "half",
  },
  jobSatisfaction: {
    labelKey: "sections.workLife.jobSatisfaction",
    type: "number",
    placeholder: t("placeholders.jobSatisfaction"),
    helpKey: "help.jobSatisfaction",
    width: "half",
    optional: true,
  },
  reports: {
    labelKey: "sections.workLife.reports",
    type: "number",
    placeholder: t("placeholders.reports"),
    helpKey: "help.reports",
    width: "half",
    optional: true,
  },
  extraNotes: {
    labelKey: "sections.notes.extraNotes",
    type: "richtext",
    placeholder: t("placeholders.extraNotes"),
    helpKey: "help.extraNotes",
    width: "full",
    optional: true,
  },
});

// Define which fields are available for each country
export const COUNTRY_FIELD_CONFIGS: Record<string, string[]> = {
  Belgium: [
    "workerType",
    "contractType",
    "contractDurationMonths",
    "age",
    "education",
    "degreeId",
    "workExperience",
    "civilStatus",
    "dependents",
    "sector",
    "employeeCount",
    "multinational",
    "publiclyListed",
    "jobTitle",
    "seniority",
    "jobDescription",
    "officialHours",
    "averageHours",
    "shiftDescription",
    "onCall",
    "grossSalary",
    "netSalary",
    "netCompensation",
    "fixedGrossSalary",
    "variableGrossSalary",
    "hourlyRate",
    "dayRate",
    "agencyCutPercent",
    "clientDayBudget",
    "bursaryAmount",
    "virtualGrossSalary",
    "thirteenthMonth",
    "mealVouchers",
    "ecoCheques",
    "groupInsurance",
    "hasCompanyCar",
    "companyCarModel",
    "companyCarFuelType",
    "companyCarCardScope",
    "hasEquity",
    "otherInsurances",
    "otherBenefits",
    "locationGranularity",
    "workProvince",
    "residenceCountry",
    "workCity",
    "commuteUnit",
    "commuteDistance",
    "commuteTimeMinutes",
    "commuteMethod",
    "commuteCompensation",
    "teleworkDays",
    "vacationDays",
    "reports",
    "dayOffEase",
    "stressLevel",
    "jobSatisfaction",
    "extraNotes",
  ],
  Netherlands: [
    "workerType",
    "contractType",
    "contractDurationMonths",
    "age",
    "education",
    "degreeId",
    "workExperience",
    "civilStatus",
    "dependents",
    "sector",
    "employeeCount",
    "multinational",
    "publiclyListed",
    "jobTitle",
    "seniority",
    "jobDescription",
    "officialHours",
    "averageHours",
    "shiftDescription",
    "onCall",
    "grossSalary",
    "netSalary",
    "netCompensation",
    "fixedGrossSalary",
    "variableGrossSalary",
    "hourlyRate",
    "dayRate",
    "agencyCutPercent",
    "clientDayBudget",
    "bursaryAmount",
    "virtualGrossSalary",
    "hasCompanyCar",
    "companyCarModel",
    "companyCarFuelType",
    "companyCarCardScope",
    "hasEquity",
    "otherInsurances",
    "otherBenefits",
    "locationGranularity",
    "residenceCountry",
    "workCity",
    "commuteUnit",
    "commuteDistance",
    "commuteTimeMinutes",
    "commuteMethod",
    "commuteCompensation",
    "teleworkDays",
    "vacationDays",
    "reports",
    "dayOffEase",
    "stressLevel",
    "jobSatisfaction",
    "extraNotes",
  ],
};

// Helper function to get field configs for a specific country
export const getFieldConfigsForCountry = (
  country: string,
  allFieldConfigs: FieldConfigs
): FieldConfigs => {
  const allowedFields = COUNTRY_FIELD_CONFIGS[country];
  if (!allowedFields) {
    return allFieldConfigs; // Return all configs if country not found
  }

  // Filter to only include fields allowed for this country
  return Object.keys(allFieldConfigs)
    .filter((key) => allowedFields.includes(key))
    .reduce((obj, key) => {
      obj[key] = allFieldConfigs[key];
      return obj;
    }, {} as FieldConfigs);
};

/**
 * Whether a given country's form actually collects (renders an input for) a
 * field. Mirrors the render-time country filter in getFieldConfigsForCountry:
 * an unknown country (or none chosen yet) falls back to "collects everything",
 * exactly as the form does. The validation schema uses this so it never marks a
 * field required for a country that has no way to enter it (which would make the
 * form silently un-submittable — the errors would attach to non-rendered inputs).
 */
export const countryCollectsField = (
  country: string | undefined | null,
  field: string
): boolean => {
  if (!country) return true;
  const allowed = COUNTRY_FIELD_CONFIGS[country];
  if (!allowed) return true;
  return allowed.includes(field);
};
