-- AlterTable
ALTER TABLE "public"."SalaryEntry" ALTER COLUMN "officialHours" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "averageHours" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "teleworkDays" SET DATA TYPE DOUBLE PRECISION;
